apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
spec:
  selector:
    matchLabels:
      app: users-api
  replicas: 1
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api-container
          image: users-api:v1.2
          imagePullPolicy: Never
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: users-api-service
spec:
  selector:
    app: users-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
